
# =======================
# Jake Carter
# New version - 2023-03-14
# =======================

# precommit hooks installation
# =======================
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# =======================
# - pre-commit autoupdate
#
# - pre-commit run black
#
# continuous integration
# ======================
#
# Manual Run
# ======================
# - pre-commit run --all-files

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
      - id: ruff
      args: [ --autofix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-builtin-literals
        stages: [ post-commit, push ]
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            .*.txt|
            .*.csv|
            .*.sdf|
            .*.pdb|
            .*.mmCIF|
            .*.smi|
            .*.tsv|
            .*.tab|
            .*.fasta|
            .*.ent|
            .*.yaml|
            out_precommit.txt|
          )$
        stages: [ post-commit, push ]
      - id: check-merge-conflict
        stages: [ post-commit, push ]
      - id: check-added-large-files
        stages: [ post-commit, push ]
      - id: check-ast
        stages: [ post-commit, push ]
      - id: check-json
        stages: [ post-commit, push ]
      - id: check-shebang-scripts-are-executable
        exclude: .*.ipynb$, __init__.py$, setup.py$
        stages: [ post-commit, push ]
      - id: check-symlinks
        stages: [ post-commit, push ]
      - id: check-toml
        additional_dependencies: [ toml ]
        stages: [ post-commit, push ]
      - id: check-vcs-permalinks
        stages: [ post-commit, push ]
      - id: check-xml
        stages: [ post-commit, push ]
      - id: check-yaml
        stages: [ post-commit, push ]
      - id: debug-statements
        stages: [ post-commit, push ]
      - id: destroyed-symlinks
        stages: [ post-commit, push ]
      - id: detect-aws-credentials
        stages: [ post-commit, push ]
      - id: detect-private-key
        stages: [ post-commit, push ]
      - id: end-of-file-fixer
        stages: [ post-commit, push ]
        exclude: .idea
      - id: mixed-line-ending
        stages: [ post-commit, push ]
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: no-commit-to-branch
        args:
          - --branch
          - dev
          - --branch
          - main
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        stages: [ post-commit, push ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        exclude: |
          (?x)^(
            .*.txt|
            .*.csv|
            .*.sdf|
            .*.pdb|
            .*.mmCIF|
            .*.smi|
            .*.tsv|
            .*.tab|
            .*.fasta|
            .*.ent|
            .*.yaml|
            .*.yml|
            /.idea*|
            out_precommit.txt|
          )$
        stages: [ post-commit, push ]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args:
          - --format
          - parsable
          - --strict
            #- -- ignore
            #- .license-check.yaml
        stages: [ post-commit, push ]
  - repo: https://gitlab.com/iamlikeme/nbhooks
    rev: 1.0.0
    hooks:
      - id: nb-ensure-clean
        args:
          - --meta
          - --ExecuteTime
        stages: [ post-commit, push ]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        stages: [ post-commit, push ]
  - repo: https://github.com/kontrolilo/kontrolilo
    rev: v2.2.0
    hooks:
      - id: license-check-configuration-lint
        stages: [ post-commit, push ]
      - id: license-check-npm
        stages: [ post-commit, push ]
      - id: license-check-pipenv
        stages: [ post-commit, push ]
  - repo: https://github.com/sirwart/ripsecrets.git
    rev: v0.1.5
    hooks:
      - id: ripsecrets
        stages: [ post-commit, push ]
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [ post-commit, push ]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.3
    hooks:
      - id: nbqa-isort
        additional_dependencies: [ isort==5.7.0 ]
        args: [ --nbqa-mutate ]
